[package]
name = "mips"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
mips_parser = { path="./crates/mips_parser/" }
thiserror = "1.0.61"
